.DEFAULT_GOAL := help
SHELL         := /bin/bash

# ── Colours ───────────────────────────────────────────────────────────────────
CYAN  := \033[0;36m
GREEN := \033[0;32m
YELLOW:= \033[0;33m
BOLD  := \033[1m
RESET := \033[0m

# ── Helpers ───────────────────────────────────────────────────────────────────
define log
	@printf "$(CYAN)$(BOLD)▶ $(1)$(RESET)\n"
endef

.PHONY: help install dev build lint test test-watch test-e2e test-all \
        db-start db-stop db-reset db-studio db-logs \
        env-local env-check setup demo demo-seed

# ── Help ──────────────────────────────────────────────────────────────────────
help: ## Show available commands
	@printf "\n$(BOLD)CrewLink — Local Development$(RESET)\n\n"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  $(CYAN)%-18s$(RESET) %s\n", $$1, $$2}'
	@printf "\n$(YELLOW)Quick start:$(RESET) make setup && make env-local && make dev\n\n"

# ── Node / App ────────────────────────────────────────────────────────────────
install: ## Install Node dependencies
	$(call log,Installing dependencies...)
	npm install

dev: ## Start Next.js dev server (http://localhost:3000)
	$(call log,Starting Next.js...)
	npm run dev

build: ## Build for production
	$(call log,Building...)
	npm run build

lint: ## Run ESLint
	npm run lint

test: ## Run unit tests (no server required)
	$(call log,Running unit tests...)
	npm test

test-watch: ## Run unit tests in watch mode
	npm run test:watch

test-e2e: ## Run E2E tests (requires: make db-start + make dev running)
	$(call log,Running E2E tests against http://localhost:3000...)
	@if ! curl -sf http://localhost:3000/api/agents/search > /dev/null 2>&1; then \
	  printf "$(YELLOW)Dev server not running. Start it first:$(RESET)\n"; \
	  printf "  $(CYAN)make dev$(RESET)  (in another terminal)\n\n"; \
	  exit 1; \
	fi
	npm run test:e2e

test-all: test test-e2e ## Run unit + E2E tests

# ── Supabase DB ───────────────────────────────────────────────────────────────
db-start: ## Start local Supabase (Docker)
	$(call log,Starting Supabase...)
	supabase start

db-stop: ## Stop local Supabase
	$(call log,Stopping Supabase...)
	supabase stop

db-reset: ## Reset DB — apply all migrations + seed data
	$(call log,Resetting database...)
	supabase db reset

db-studio: ## Open Supabase Studio in browser
	$(call log,Opening Studio...)
	open http://localhost:54323 2>/dev/null || xdg-open http://localhost:54323

db-logs: ## Tail Supabase DB logs
	supabase logs db

# ── Environment ───────────────────────────────────────────────────────────────
env-local: ## Generate .env.local from running local Supabase instance
	$(call log,Generating .env.local...)
	@if ! supabase status > /dev/null 2>&1; then \
	  printf "$(YELLOW)Supabase not running. Run: make db-start$(RESET)\n"; exit 1; \
	fi
	@SUPABASE_URL=$$(supabase status | grep "API URL" | awk '{print $$NF}'); \
	ANON_KEY=$$(supabase status | grep "anon key" | awk '{print $$NF}'); \
	SERVICE_KEY=$$(supabase status | grep "service_role key" | awk '{print $$NF}'); \
	JWT_SECRET=$$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"); \
	if [ -f .env.local ]; then \
	  printf "$(YELLOW).env.local already exists — updating Supabase vars only$(RESET)\n"; \
	  grep -v "^NEXT_PUBLIC_SUPABASE_\|^SUPABASE_SERVICE_ROLE_KEY" .env.local > .env.local.tmp || true; \
	  mv .env.local.tmp .env.local; \
	fi; \
	printf "\n# Supabase (auto-generated by make env-local)\n" >> .env.local; \
	printf "NEXT_PUBLIC_SUPABASE_URL=%s\n" "$$SUPABASE_URL" >> .env.local; \
	printf "NEXT_PUBLIC_SUPABASE_ANON_KEY=%s\n" "$$ANON_KEY" >> .env.local; \
	printf "SUPABASE_SERVICE_ROLE_KEY=%s\n" "$$SERVICE_KEY" >> .env.local; \
	if ! grep -q "AGENT_JWT_SECRET" .env.local 2>/dev/null; then \
	  printf "\n# Agent JWT (auto-generated)\n" >> .env.local; \
	  printf "AGENT_JWT_SECRET=%s\n" "$$JWT_SECRET" >> .env.local; \
	fi; \
	printf "$(GREEN)✓ .env.local updated$(RESET)\n"; \
	printf "\n$(YELLOW)Still needed (add manually to .env.local):$(RESET)\n"; \
	printf "  CLERK_SECRET_KEY=sk_test_...\n"; \
	printf "  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_...\n"; \
	printf "  NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in\n"; \
	printf "  NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up\n"; \
	printf "  CLERK_WEBHOOK_SECRET=whsec_...\n"; \
	printf "  STRIPE_SECRET_KEY=sk_test_... (optional)\n"; \
	printf "  STRIPE_WEBHOOK_SECRET=whsec_... (optional)\n\n"

env-check: ## Verify required env vars are present in .env.local
	$(call log,Checking environment...)
	@node -e " \
	  const fs = require('fs'); \
	  const env = {}; \
	  try { \
	    fs.readFileSync('.env.local','utf8').split('\n').forEach(l => { \
	      const m = l.match(/^([A-Z_]+)=(.+)/); if(m) env[m[1]]=m[2]; \
	    }); \
	  } catch(e) {} \
	  const required = ['NEXT_PUBLIC_SUPABASE_URL','NEXT_PUBLIC_SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY','AGENT_JWT_SECRET']; \
	  const optional = ['CLERK_SECRET_KEY','STRIPE_SECRET_KEY','UPSTASH_REDIS_REST_URL']; \
	  let ok = true; \
	  required.forEach(k => { \
	    if(!env[k]) { console.log('  ✗ '+k+' (REQUIRED)'); ok=false; } \
	    else console.log('  ✓ '+k); \
	  }); \
	  optional.forEach(k => { \
	    console.log('  '+(env[k]?'✓':'○')+' '+k+(env[k]?'':' (optional)')); \
	  }); \
	  if(!ok) { console.log('\nRun: make env-local'); process.exit(1); } \
	"

# ── Demo ──────────────────────────────────────────────────────────────────────
demo-seed: ## Create demo owner with 10 000 credits (local Supabase only)
	$(call log,Seeding demo owner...)
	@node -e " \
	  const fs = require('fs'); \
	  const {createHash, randomBytes} = require('crypto'); \
	  const env = {}; \
	  try { fs.readFileSync('.env.local','utf8').split('\n').forEach(l => { \
	    const m = l.match(/^([A-Z_0-9a-z_]+)=(.+)/); if(m) env[m[1].trim()]=m[2].trim(); \
	  }); } catch(e) {} \
	  const url = env['NEXT_PUBLIC_SUPABASE_URL'] || 'http://localhost:54321'; \
	  const key = env['SUPABASE_SERVICE_ROLE_KEY']; \
	  if (!key) { console.error('SUPABASE_SERVICE_ROLE_KEY not set. Run: make env-local'); process.exit(1); } \
	  const raw = 'crewlink_demo_' + randomBytes(16).toString('base64url'); \
	  const hash = createHash('sha256').update(raw).digest('hex'); \
	  fetch(url+'/rest/v1/users', { \
	    method: 'POST', \
	    headers: { 'apikey': key, 'Authorization': 'Bearer '+key, 'Content-Type': 'application/json', 'Prefer': 'return=representation,resolution=merge-duplicates' }, \
	    body: JSON.stringify({ clerk_user_id: 'demo_local', email: 'demo@crewlink.local', credits_balance: 10000, api_key_hash: hash, approval_threshold: 9999, is_active: true }), \
	  }).then(async r => { \
	    if (!r.ok) { const t = await r.text(); console.error('Failed:', t); process.exit(1); } \
	    const d = await r.json(); \
	    console.log(''); \
	    console.log('  Owner user_id : ' + (Array.isArray(d) ? d[0].id : d.id)); \
	    console.log('  Credits       : 10 000'); \
	    console.log(''); \
	    console.log('Add to .env.local:'); \
	    console.log('  OWNER_API_KEY=' + raw); \
	    console.log(''); \
	  }).catch(e => { console.error(e.message); process.exit(1); }); \
	"

demo: ## Run 2-agent demo (register → job → apply → hire → complete → rate)
	$(call log,Running 2-agent demo...)
	@node scripts/demo-agents.mjs

# ── Full setup ────────────────────────────────────────────────────────────────
setup: install db-start db-reset env-local ## Full local setup: install + DB + migrations + .env.local
	@printf "\n$(GREEN)$(BOLD)Setup complete!$(RESET)\n"
	@printf "Next steps:\n"
	@printf "  1. Add Clerk keys to .env.local\n"
	@printf "  2. Run: $(CYAN)make dev$(RESET)\n"
	@printf "  3. Sign in at http://localhost:3000 to get your OWNER_API_KEY\n"
	@printf "  4. Run: $(CYAN)make demo$(RESET)\n\n"
